### ISSUE TITLE
Error when typing value for subscope attribute

### ISSUE THREAD

**Issue by kyoz** [ncm2/ncm2-html-subscope#1]
When using ncm2 with ncm2-html-subscope. It work normally but when i typing value for subscope attribute, the cursor always return to the start of the line (at 3rd character). See this gif:

![nvim subscope error html](https://user-images.githubusercontent.com/29815830/48609800-a5d01f80-e9b6-11e8-8847-669bee85f98f.gif)

### OS

Ubuntu 16.04, 18.04. MacOS Mojave

### Minimal vimrc for reproducing the issue
```
call plug#begin('~/.config/nvim/plugged')

Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'ncm2/ncm2-html-subscope'

call plug#end()

autocmd BufEnter * call ncm2#enable_for_buffer()
set completeopt=noinsert,menuone,noselect
set shortmess+=c

au User Ncm2Plugin call ncm2#register_source({
  \ 'name' : 'html',
  \ 'priority': 9,
  \ 'subscope_enable': 1,
  \ 'scope': ['html'],
  \ 'mark': 'html',
  \ 'complete_pattern': ['\<'],
  \ 'word_pattern': '[\w-]+',
  \ 'on_complete': ['ncm2#on_complete#omni', 'htmlcomplete#CompleteTags'],
  \ })
```
Don't know if i register source for ncm2 correctly, but i'v tried a lot of config and it still there. :cry:

**Comment by roxma** [comment]
This is probably `htmlcomplete` issue.

You could add `  \ 'complete_length': -1,` disable word completion.

```vim
au User Ncm2Plugin call ncm2#register_source({
  \ 'name' : 'html',
  \ 'priority': 9,
  \ 'subscope_enable': 1,
  \ 'scope': ['html'],
  \ 'mark': 'html',
  \ 'complete_length': -1,
  \ 'complete_pattern': ['\<'],
  \ 'word_pattern': '[\w-]+',
  \ 'on_complete': ['ncm2#on_complete#omni', 'htmlcomplete#CompleteTags'],
  \ })
```

**Comment by kyoz** [comment]
Hi @roxma this issue is cause by htmlcomplete, mean it's on neovim project right. I think i should open a issue in there. I do use html almost all the time, without attribute complete it's really painful 😢
